In [1]:
import numpy as np

Giả sử chúng ta có ma trận `ratings`, trong đó các phần từ thể hiện điểm số mà user đánh giá anime tương ứng

In [2]:
ratings = np.array([[5, 4, np.nan, 1, np.nan], [np.nan, 4, 4, 2, 2],
                    [3, np.nan, np.nan, 5, 5],[np.nan, 3, 4, 4, np.nan]])
ratings

array([[ 5.,  4., nan,  1., nan],
       [nan,  4.,  4.,  2.,  2.],
       [ 3., nan, nan,  5.,  5.],
       [nan,  3.,  4.,  4., nan]])

In [3]:
np.set_printoptions(suppress = True)

Ở đây mình chỉ tính trên 1 user thôi :v còn phần tính trên batch (nhiều user) các bạn sẽ cơ hội tự trải nghiệm. Chúng ta sẽ xây dựng một mô hình đơn giản để dự đoán các phim mà user chưa đánh gía, hay nói cách khác là các ô `NaN`. Đầu tiên, chúng ta tưởng tượng mỗi dòng là một vector ứng với một user. Sau đó, chúng ta tính toán độ tương tự giữa các vector thông qua khoảng cách. 

In [4]:
# Lấy ra user đầu tiên
r0 = ratings[0]
# Lấy tất cả các user trừ cho user đầu tiên để tính khoảng cách, 
# sau đó tính mean của từng dòng để thu được độ tương tự giữa các user đối với user[0]
s = np.nanmean(np.abs(ratings - r0), axis = 1)
s = 1/(s + 0.001)
s

array([1000.        ,    1.99600798,    0.33322226,    0.49975012])

In [12]:
# Lấy ra các cột mà user[0] chưa đánh giá để 
# print(np.isnan(r0).shape)
# result = []

# for i in range(ratings.shape[0]):
#     ri = ratings[i]
#     ai = ratings[:, np.isnan(ri)]
#     result.append(ai)
# print(len(result))
# print(result[0].shape)
# # result = np.array(result)
# # Lọc những cột chứa NaN
# # result = result & nan_columns[:, np.newaxis, :]
# mask = np.isnan(ratings)
# result = np.concatenate([ratings[:, mask[i]] for i in range(mask.shape[0])], axis=1)

# # print(result.shape)


# a = ratings[:, np.isnan(r0)]
# a

# Tạo ma trận có shape (3, 4, 5)
matrix_3d = np.random.random((3, 4, 5))
print('3d',matrix_3d)
# Tạo ma trận có shape (4, 5)
matrix_2d = np.random.random((4, 5))
print('2d',matrix_2d)
# Thực hiện phép nhân element-wise
result_matrix = matrix_3d * matrix_2d
print('result:',result_matrix)

3d [[[0.97806824 0.07377961 0.11123067 0.95653025 0.83327877]
  [0.44636775 0.97578755 0.36574642 0.11477824 0.32846164]
  [0.02027894 0.34712998 0.8171015  0.62691462 0.5292967 ]
  [0.97982345 0.40308471 0.18733656 0.89423078 0.7417312 ]]

 [[0.20636667 0.12704115 0.52774816 0.46252336 0.40312353]
  [0.19552382 0.53200505 0.64403561 0.75735924 0.51665121]
  [0.20828042 0.28636336 0.2972836  0.92786791 0.57556074]
  [0.06705071 0.33790972 0.74493346 0.49325992 0.85639498]]

 [[0.77084709 0.13468825 0.59676147 0.93093366 0.13689631]
  [0.50271967 0.42391422 0.5738828  0.72988695 0.36130573]
  [0.5001008  0.26989441 0.75654247 0.66804606 0.70775737]
  [0.51496587 0.7155044  0.4421402  0.08542287 0.40132129]]]
2d [[0.09163752 0.20058761 0.37202503 0.69118558 0.83493256]
 [0.54570137 0.38107115 0.56975489 0.08376107 0.69251549]
 [0.26955049 0.00517193 0.33243179 0.39103873 0.96926602]
 [0.96554771 0.99757372 0.90300296 0.7552617  0.76370803]]
result: [[[0.08962775 0.01479927 0.04138059 0.6

In [6]:
# Tạo ma trận trọng số dựa trên độ tương tự
w = ~np.isnan(a)*s.reshape(-1, 1)
print(np.isnan(a).shape)
print(s.reshape(-1, 1).shape)
# Chuẩn hoá trọng số
w = w/w.sum(axis = 0)
print(w.shape)
w

(4, 2)
(4, 1)
(4, 2)


array([[0.        , 0.        ],
       [0.79976019, 0.85693889],
       [0.        , 0.14306111],
       [0.20023981, 0.        ]])

In [7]:
# Kết quả dự đoán được
np.nansum(a*w, axis = 0)

array([4.        , 2.42918332])